import * as fs from 'fs';
import * as path from 'path';
import { loadGraph } from '../graph/store';
import { graphToMarkdown } from '../compiler/graphToMarkdown';
import { NodeType, SpecNode } from '../types';
import { emit } from '../output';

export interface ExportAllOpts {
  pretty?: boolean;
  outDir?: string;
}

const TYPE_HEADING: Record<NodeType, string> = {
  requirement: 'Requirements',
  entity: 'Entities',
  workflow: 'Workflows',
  api: 'APIs'
};

const TYPE_ORDER: NodeType[] = ['requirement', 'entity', 'workflow', 'api'];

const DO_NOT_EDIT = '<!-- DO NOT EDIT — regenerate via `pv export-all`. Source: .polaris/graph.json -->';

export function runExportAll(opts: ExportAllOpts = {}): void {
  const cwd = process.cwd();
  const outDir = path.resolve(cwd, opts.outDir || 'spec');

  fs.mkdirSync(outDir, { recursive: true });

  const graph = loadGraph(cwd);
  const written: string[] = [];

  // Write per-node markdown files.
  for (const node of Object.values(graph.nodes)) {
    const body = graphToMarkdown(node, graph, { linkTargets: true });
    const content = `${DO_NOT_EDIT}\n\n${body}`;
    const filePath = path.join(outDir, `${node.id}.md`);
    fs.writeFileSync(filePath, content, 'utf8');
    written.push(path.relative(cwd, filePath));
  }

  // Write the index.
  const indexMd = renderIndex(Object.values(graph.nodes));
  const indexPath = path.join(outDir, 'README.md');
  fs.writeFileSync(indexPath, indexMd, 'utf8');
  written.push(path.relative(cwd, indexPath));

  emit(
    {
      ok: true,
      out_dir: path.relative(cwd, outDir),
      files_written: written.length,
      files: written.sort()
    },
    { pretty: opts.pretty }
  );
}

function renderIndex(nodes: SpecNode[]): string {
  const byDomain = new Map<string, Map<NodeType, SpecNode[]>>();
  for (const node of nodes) {
    if (!byDomain.has(node.domain)) byDomain.set(node.domain, new Map());
    const typeMap = byDomain.get(node.domain)!;
    if (!typeMap.has(node.type)) typeMap.set(node.type, []);
    typeMap.get(node.type)!.push(node);
  }

  const lines: string[] = [];
  lines.push(DO_NOT_EDIT);
  lines.push('');
  lines.push('# Spec — auto-generated from `.polaris/graph.json`');
  lines.push('');
  lines.push(
    'This directory is the human-readable view of the spec graph. **Do not hand-edit** — every file here is regenerated by `pv export-all`. The graph at [`.polaris/graph.json`](../.polaris/graph.json) is the source of truth; treat this directory as a derived artifact, like compiled code.'
  );
  lines.push('');

  // Summary line.
  const total = nodes.length;
  const domains = Array.from(byDomain.keys()).sort();
  lines.push(`**${total} nodes** across **${domains.length} domain(s)**: ${domains.join(', ')}.`);
  lines.push('');

  for (const domain of domains) {
    const typeMap = byDomain.get(domain)!;
    lines.push(`## ${domain}`);
    lines.push('');

    for (const type of TYPE_ORDER) {
      const list = typeMap.get(type);
      if (!list || list.length === 0) continue;
      list.sort((a, b) => a.id.localeCompare(b.id));
      lines.push(`### ${TYPE_HEADING[type]} (${list.length})`);
      lines.push('');
      for (const node of list) {
        lines.push(`- [${node.id}](${node.id}.md) — ${node.title}`);
      }
      lines.push('');
    }
  }

  lines.push('---');
  lines.push('');
  lines.push('_Regenerate this directory with `pv export-all`._');
  lines.push('');
  return lines.join('\n');
}
