import * as fs from 'fs';
import * as path from 'path';
import { loadGraph, loadCodeMap } from '../graph/store';
import { graphToMarkdown } from '../compiler/graphToMarkdown';
import { graphToDomainPage } from '../compiler/graphToDomainPage';
import { NodeType, SpecNode } from '../types';
import { emit } from '../output';

export interface ExportAllOpts {
  pretty?: boolean;
  outDir?: string;
}

const DO_NOT_EDIT = '<!-- DO NOT EDIT — regenerate via `pv export-all`. Source: .polaris/graph.json -->';

// Matches generated per-node files: PREFIX-DOMAIN-... .md
// (REQ-AUTH-001.md, API-AUTH-LOGIN.md, ENT-AUTH-USER.md, ...).
// Limits deletion to files we actually generate, so a user-added
// note like spec/NOTES.md is left alone.
const NODE_FILE_RE = /^[A-Z]+-[A-Z0-9]+-.+\.md$/;

// Matches generated per-domain narrative pages: a single uppercase
// segment followed by `.md` (AUTH.md, BILLING.md, PV.md). Distinguishes
// from per-id files (which have at least 3 segments separated by `-`)
// and from README.md.
const DOMAIN_PAGE_RE = /^[A-Z][A-Z0-9]*\.md$/;

export function runExportAll(opts: ExportAllOpts = {}): void {
  const cwd = process.cwd();
  const outDir = path.resolve(cwd, opts.outDir || 'spec');

  fs.mkdirSync(outDir, { recursive: true });

  const graph = loadGraph(cwd);
  const codemap = loadCodeMap(cwd);
  const written: string[] = [];
  const removed: string[] = [];

  // Stale-file removal — covers two file shapes we generate:
  //   1. spec/<id>.md per node — gone if its node was deleted from the graph
  //   2. spec/<DOMAIN>.md per domain — gone if no node uses that domain anymore
  // Without this, a deleted node or domain leaves an orphan markdown that
  // CI's `git diff --quiet spec/` check can't catch (no diff = no signal).
  const currentIds = new Set(Object.keys(graph.nodes));
  const currentDomains = new Set(Object.values(graph.nodes).map((n) => n.domain));
  for (const file of fs.readdirSync(outDir)) {
    if (file === 'README.md') continue;
    const stalePath = path.join(outDir, file);
    if (NODE_FILE_RE.test(file)) {
      const id = file.replace(/\.md$/, '');
      if (!currentIds.has(id)) {
        fs.unlinkSync(stalePath);
        removed.push(path.relative(cwd, stalePath));
      }
    } else if (DOMAIN_PAGE_RE.test(file)) {
      // Stricter check than NODE_FILE_RE: many user-curated files
      // happen to match `[A-Z]+\.md` (CHANGELOG, NOTES, TODO, …).
      // Only delete if the file was generated by us — detected via
      // our DO_NOT_EDIT marker on the first line.
      const domain = file.replace(/\.md$/, '');
      if (!currentDomains.has(domain) && wasGeneratedByUs(stalePath)) {
        fs.unlinkSync(stalePath);
        removed.push(path.relative(cwd, stalePath));
      }
    }
  }

  // Per-node detail pages — the "API reference" of the spec; powers
  // PR-diff granularity and `pv promote` round-trip.
  for (const node of Object.values(graph.nodes)) {
    const body = graphToMarkdown(node, graph, { linkTargets: true });
    const content = `${DO_NOT_EDIT}\n\n${body}`;
    const filePath = path.join(outDir, `${node.id}.md`);
    fs.writeFileSync(filePath, content, 'utf8');
    written.push(path.relative(cwd, filePath));
  }

  // Per-domain narrative pages — the "guide" of the spec; what a
  // human actually wants to *read* end-to-end. Single page per domain
  // with all nodes inlined and grouped by type.
  for (const domain of Array.from(currentDomains).sort()) {
    const body = graphToDomainPage(domain, graph, codemap);
    const content = `${DO_NOT_EDIT}\n\n${body}`;
    const filePath = path.join(outDir, `${domain}.md`);
    fs.writeFileSync(filePath, content, 'utf8');
    written.push(path.relative(cwd, filePath));
  }

  // README — top-level index pointing at domain pages, with a quick
  // ID-by-domain lookup for deep linking.
  const indexMd = renderIndex(Object.values(graph.nodes), currentDomains);
  const indexPath = path.join(outDir, 'README.md');
  fs.writeFileSync(indexPath, indexMd, 'utf8');
  written.push(path.relative(cwd, indexPath));

  emit(
    {
      ok: true,
      out_dir: path.relative(cwd, outDir),
      files_written: written.length,
      files_removed: removed.length,
      files: written.sort(),
      removed: removed.sort()
    },
    { pretty: opts.pretty }
  );
}

/** True if the file's first line carries our `DO_NOT_EDIT` marker —
 *  i.e. it was generated by a previous `pv export-all`. Used to keep
 *  user-curated files (CHANGELOG.md, NOTES.md) from being deleted as
 *  fake "stale domain pages". */
function wasGeneratedByUs(filePath: string): boolean {
  try {
    const head = fs.readFileSync(filePath, 'utf8').slice(0, DO_NOT_EDIT.length + 4);
    return head.startsWith(DO_NOT_EDIT);
  } catch {
    return false;
  }
}

function renderIndex(nodes: SpecNode[], domains: Set<string>): string {
  const sortedDomains = Array.from(domains).sort();
  const byDomain = new Map<string, SpecNode[]>();
  for (const node of nodes) {
    const list = byDomain.get(node.domain) ?? [];
    list.push(node);
    byDomain.set(node.domain, list);
  }
  for (const list of byDomain.values()) list.sort((a, b) => a.id.localeCompare(b.id));

  const lines: string[] = [];
  lines.push(DO_NOT_EDIT);
  lines.push('');
  lines.push('# Spec — auto-generated from `.polaris/graph.json`');
  lines.push('');
  lines.push(
    'This directory is the human-readable view of the Intent graph. **Do not hand-edit** — every file is regenerated by `pv export-all`. The graph at [`.polaris/graph.json`](../.polaris/graph.json) is the source of truth.'
  );
  lines.push('');

  lines.push(
    `**${nodes.length} nodes** across **${sortedDomains.length} domain${sortedDomains.length === 1 ? '' : 's'}**.`
  );
  lines.push('');

  // Domain narrative pages — the recommended entry points for reading.
  lines.push('## Domain pages (read these first)');
  lines.push('');
  lines.push(
    'One page per domain, all that domain\'s nodes inlined and grouped by type. The natural unit for reading the spec end-to-end.'
  );
  lines.push('');
  for (const domain of sortedDomains) {
    const list = byDomain.get(domain) ?? [];
    lines.push(`- **[${domain}](${domain}.md)** — ${list.length} node${list.length === 1 ? '' : 's'}`);
  }
  lines.push('');

  // Per-id quick lookup — collapsed by default to keep README scannable
  // even on large graphs. Useful for deep-linking and PR diffs.
  lines.push('## Per-node detail pages');
  lines.push('');
  lines.push(
    '_Each node also has its own page (used by PR diffs and `pv promote` round-trip)._'
  );
  lines.push('');
  for (const domain of sortedDomains) {
    const list = byDomain.get(domain) ?? [];
    lines.push(`<details><summary><strong>${domain}</strong> (${list.length})</summary>`);
    lines.push('');
    for (const n of list) {
      lines.push(`- [\`${n.id}\`](${n.id}.md) — ${n.title}`);
    }
    lines.push('');
    lines.push('</details>');
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push('_Regenerate this directory with `pv export-all`._');
  lines.push('');
  return lines.join('\n');
}
