import { Graph, SpecNode } from '../types';
import { incoming } from '../graph/ops';

export function graphToMarkdown(node: SpecNode, graph: Graph): string {
  const lines: string[] = [];
  lines.push(`# ${node.id} — ${node.title}`);
  lines.push('');
  lines.push(`- **Type:** ${node.type}`);
  lines.push(`- **Domain:** ${node.domain}`);
  if (node.tags.length > 0) {
    lines.push(`- **Tags:** ${node.tags.map((t) => `\`${t}\``).join(', ')}`);
  }
  lines.push(`- **Created:** ${node.createdAt}`);
  lines.push('');

  if (node.description) {
    lines.push('## Description');
    lines.push('');
    lines.push(node.description);
    lines.push('');
  }

  if (node.relations.length > 0) {
    lines.push('## Outgoing relations');
    lines.push('');
    for (const rel of node.relations) {
      const targetTitle = graph.nodes[rel.target]?.title ?? '(missing)';
      lines.push(`- **${rel.type}** → \`${rel.target}\` — ${targetTitle}`);
    }
    lines.push('');
  }

  const inc = incoming(graph, node.id);
  if (inc.length > 0) {
    lines.push('## Incoming relations');
    lines.push('');
    for (const edge of inc) {
      const sourceTitle = graph.nodes[edge.from]?.title ?? '(missing)';
      lines.push(`- \`${edge.from}\` — ${sourceTitle} **${edge.type}** → this`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push('_Generated by Polaris Vibe Spec. Do not edit by hand — graph is the source of truth._');
  lines.push('');

  return lines.join('\n');
}
