import { Graph, SpecNode } from '../types';
import { incoming } from '../graph/ops';

export interface MarkdownOptions {
  /**
   * If true, render relation targets as relative Markdown links to
   * `<target>.md`. Use when emitting into a directory of per-node files
   * (e.g. via `pv export-all`). When false, render as inline code spans —
   * appropriate for stdout use of `pv export <id>`.
   */
  linkTargets?: boolean;
}

export function graphToMarkdown(
  node: SpecNode,
  graph: Graph,
  opts: MarkdownOptions = {}
): string {
  const lines: string[] = [];
  const linkOf = (id: string) =>
    opts.linkTargets ? `[${id}](${id}.md)` : `\`${id}\``;

  lines.push(`# ${node.id} — ${node.title}`);
  lines.push('');
  lines.push(`- **Type:** ${node.type}`);
  lines.push(`- **Domain:** ${node.domain}`);
  if (node.tags.length > 0) {
    lines.push(`- **Tags:** ${node.tags.map((t) => `\`${t}\``).join(', ')}`);
  }
  lines.push(`- **Created:** ${node.createdAt}`);
  lines.push('');

  if (node.description) {
    lines.push('## Description');
    lines.push('');
    lines.push(node.description);
    lines.push('');
  }

  if (node.relations.length > 0) {
    lines.push('## Outgoing relations');
    lines.push('');
    for (const rel of node.relations) {
      const targetTitle = graph.nodes[rel.target]?.title ?? '(missing)';
      lines.push(`- **${rel.type}** → ${linkOf(rel.target)} — ${targetTitle}`);
    }
    lines.push('');
  }

  const inc = incoming(graph, node.id);
  if (inc.length > 0) {
    lines.push('## Incoming relations');
    lines.push('');
    for (const edge of inc) {
      const sourceTitle = graph.nodes[edge.from]?.title ?? '(missing)';
      lines.push(`- ${linkOf(edge.from)} — ${sourceTitle} **${edge.type}** → this`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push('_Generated by Polaris Vibe Spec. Do not edit by hand — regenerate via `pv export-all`. The graph at `.polaris/graph.json` is the source of truth._');
  lines.push('');

  return lines.join('\n');
}
