import { RelationType, RELATION_TYPES } from '../types';

/**
 * Parse a `pv export-all`-style spec/<id>.md file back into structured
 * fields so `pv promote` can detect what the user changed and decide
 * whether the change is safe to apply to the graph or must be rejected
 * (structural changes to id / type / domain / relations require an
 * explicit graph edit, not a markdown edit).
 *
 * The parser is forgiving: missing optional sections (no Tags line, no
 * description) parse as `null`/`''`, not as errors. Only a missing or
 * malformed H1 is a hard error — without an id+title we have nothing to
 * compare against.
 */

export interface ParsedRelation {
  type: RelationType;
  target: string;
}

export interface ParsedSpec {
  id: string | null;
  title: string | null;
  type: string | null;
  domain: string | null;
  /** null = no Tags line in markdown (treat as "no change"); [] = explicit empty list */
  tags: string[] | null;
  createdAt: string | null;
  description: string;
  outgoing: ParsedRelation[];
  errors: string[];
}

const RE_H1 = /^# (\S+)\s+—\s+(.+)$/m;
const RE_TYPE = /^- \*\*Type:\*\*\s+(\S+)/m;
const RE_DOMAIN = /^- \*\*Domain:\*\*\s+(\S+)/m;
const RE_TAGS = /^- \*\*Tags:\*\*\s+(.+)$/m;
const RE_CREATED = /^- \*\*Created:\*\*\s+(\S+)/m;

const RE_SECTION_DESC = /\n## Description\s*\n([\s\S]*?)(?=\n## |\n---|\n_Generated by|$)/;
const RE_SECTION_OUT = /\n## Outgoing relations\s*\n([\s\S]*?)(?=\n## |\n---|\n_Generated by|$)/;

// Outgoing relation list line:
//   - **<type>** → [<target>](<target>.md) — <title>
//   - **<type>** → `<target>` — <title>           (stdout/code-span form)
const RE_RELATION = /^- \*\*(\w+)\*\*\s+→\s+(?:\[([^\]]+)\]\([^)]+\)|`([^`]+)`)/;

export function parseSpec(md: string): ParsedSpec {
  const result: ParsedSpec = {
    id: null,
    title: null,
    type: null,
    domain: null,
    tags: null,
    createdAt: null,
    description: '',
    outgoing: [],
    errors: []
  };

  const h1 = md.match(RE_H1);
  if (!h1) {
    result.errors.push('missing or malformed H1 heading (expected "# <ID> — <Title>")');
  } else {
    result.id = h1[1];
    result.title = h1[2].trim();
  }

  const t = md.match(RE_TYPE);
  if (t) result.type = t[1];

  const d = md.match(RE_DOMAIN);
  if (d) result.domain = d[1];

  const tags = md.match(RE_TAGS);
  if (tags) {
    result.tags = tags[1]
      .split(',')
      .map((s) => s.trim().replace(/^`|`$/g, ''))
      .filter((s) => s.length > 0);
  }

  const created = md.match(RE_CREATED);
  if (created) result.createdAt = created[1];

  const desc = md.match(RE_SECTION_DESC);
  if (desc) result.description = desc[1].trim();

  const out = md.match(RE_SECTION_OUT);
  if (out) {
    for (const rawLine of out[1].split('\n')) {
      const m = rawLine.match(RE_RELATION);
      if (!m) continue;
      const type = m[1] as RelationType;
      const target = m[2] || m[3];
      if (RELATION_TYPES.includes(type) && target) {
        result.outgoing.push({ type, target });
      }
    }
  }

  return result;
}
