#!/usr/bin/env python3
"""
Format `pv changed --pretty` JSON output as a Markdown PR comment.

Used by .github/workflows/pv-changed.yml (the PR-time intent-drift gate).
Emits a comment that:
- Summarizes diff size + linked-intent reach
- Highlights any error/warn findings with the suggested fix command
- Hides info-level (linked_node) findings inside <details> so the
  comment stays scannable but the reviewer can expand for the full
  context

Usage:  pv-changed-comment.py <pv-changed-json-file>
Output: Markdown to stdout (always emits the bot marker as line 1
        so the workflow can find an existing comment to update).
"""

import json
import sys


# Marker the workflow uses to find an existing comment to update.
MARKER = "<!-- pv-changed-bot -->"

INFO_PRD_CAP = 3       # cap PRD references rendered inside info findings
MAX_INLINE_FINDINGS = 50  # safety cap on bullet count


def emit(json_path: str) -> str:
    with open(json_path, encoding="utf-8") as f:
        data = json.load(f)

    summary = data.get("summary", {}) or {}
    findings = data.get("findings", []) or []
    base = data.get("base", "?")

    out = [MARKER, "## 🧭 PV intent-drift gate", ""]
    out.append(f"**Base:** `{base}`  ")
    out.append(f"**Files in diff:** {summary.get('files_in_diff', 0)}  ")
    out.append(f"**Linked Intents touched:** {summary.get('linked_nodes_touched', 0)}  ")
    out.append(f"**Linked PRDs touched:** {summary.get('linked_prds_touched', 0)}  ")
    out.append("")

    errors = [f for f in findings if f.get("severity") == "error"]
    warns = [f for f in findings if f.get("severity") == "warn"]
    infos = [f for f in findings if f.get("severity") == "info"]

    if summary.get("files_in_diff", 0) == 0:
        out.append("ℹ️ _No source-file changes detected against the base._")
    elif not errors and not warns:
        out.append("✅ **No structural drift detected.**")
    else:
        n = len(errors) + len(warns)
        out.append(f"⚠️ **{n} issue{'s' if n != 1 else ''} need attention.**")
        out.append("")

        if errors:
            out.append(f"### ❌ Errors ({len(errors)})")
            for f in errors[:MAX_INLINE_FINDINGS]:
                _render_finding_bullet(out, f)
            if len(errors) > MAX_INLINE_FINDINGS:
                out.append(f"- _… {len(errors) - MAX_INLINE_FINDINGS} more error(s) truncated_")
            out.append("")

        if warns:
            out.append(f"### ⚠️ Warnings ({len(warns)})")
            for f in warns[:MAX_INLINE_FINDINGS]:
                _render_finding_bullet(out, f)
            if len(warns) > MAX_INLINE_FINDINGS:
                out.append(f"- _… {len(warns) - MAX_INLINE_FINDINGS} more warning(s) truncated_")
            out.append("")

    if infos:
        out.append("")
        out.append("<details>")
        out.append(f"<summary>{len(infos)} linked-Intent finding(s) (informational)</summary>")
        out.append("")
        for f in infos[:MAX_INLINE_FINDINGS]:
            _render_finding_bullet(out, f)
        if len(infos) > MAX_INLINE_FINDINGS:
            out.append(f"- _… {len(infos) - MAX_INLINE_FINDINGS} more truncated_")
        out.append("")
        out.append("</details>")
        out.append("")

    out.append("---")
    out.append(
        "_Generated by `pv changed` ([Polaris Vibe Spec](https://github.com/miles-hs-lee/PolarisVibeSpec))._"
    )
    return "\n".join(out)


def _render_finding_bullet(out: list, f: dict) -> None:
    out.append(f"- {f.get('message', '_(no message)_')}")
    suggested = f.get("suggested_action")
    if suggested:
        out.append(f"  - Suggested: `{suggested}`")
    prds = f.get("linked_prds") or []
    for prd in prds[:INFO_PRD_CAP]:
        out.append(
            f"  - PRD section: `{prd.get('path')}` / \"{prd.get('section')}\""
        )
    if len(prds) > INFO_PRD_CAP:
        out.append(f"  - _… {len(prds) - INFO_PRD_CAP} more PRD section(s)_")


def main() -> None:
    if len(sys.argv) < 2:
        sys.stderr.write("usage: pv-changed-comment.py <json-file>\n")
        sys.exit(2)
    sys.stdout.write(emit(sys.argv[1]) + "\n")


if __name__ == "__main__":
    main()
